### ISSUE TITLE
Clicking on download redirects to a different page

### ISSUE THREAD

**Issue by pdbits** [gantt/downloadyoutube#101]
v1.8.9/Win/Firefox51(64-bit)

I had the following issue with the previous version of the script as well. After clicking the download button(both 360p and 720p), it redirects to a page on which the video is streaming. The address is usually this... https://r20---sn-h557snel.googlevideo.com/videoplayback?xxxxxx

The video can then be downloaded using that link, but then it only saves with the filename 'videoplayback'.

Kindly assist with this issue.

**Comment by EverEve** [comment]
I confirm the issue (Firefox 52.0 Beta6, both on Windows 7 and Linux).

**Comment by gantt** [comment]
If you're using the standalone extension, this shouldn't happen.

If you're using the Greasemonkey script, this is a known issue, at least for 360p. I've explained in one of the previous bug reports that YouTube changed the HTTP headers it sends for 360p videos and now Firefox treats them as regular MP4 videos, so it starts playing them in a new tab. YouTube used to force browsers to download videos and also sent the filename when passed as a parameter, but now it no longer works this way.

I don't know a reliable workaround for this. The HTML5 download attribute doesn't work because it requires same-origin URLs and download URLs use a different domain. There's another workaround that uses blobs, but there are several issues (it uses your computer's RAM, it downloads files in the background).

**Comment by pdbits** [comment]
Yes, I'm using the Greasemonkey script itself. I apologize for not going through the bug report history before reporting. I'll try the extension now. 
Can you kindly confirm if this is the correct extension as the developer name is different on the mozilla add-ons page ? Thank you.

https://addons.mozilla.org/en-US/firefox/addon/download-youtube/

I really appreciate the work that you have put in and the script has been really helpful.

**Comment by gantt** [comment]
Yes, it is

**Comment by pdbits** [comment]
Thanks.
