### ISSUE TITLE
No valid filetype für m4a download

### ISSUE THREAD

**Issue by tom987** [gantt/downloadyoutube#30]
Hi,

I can't download the audio file of this video, the filetype offered is "Text Document" instead od M4A. I tried to download it several times in recent weeks but the same error frequently occurs.  

https://www.youtube.com/watch?v=A4-ibbvauwg

tom

**Comment by gantt** [comment]
I used the Firefox extension and enabled dash in about:config. It worked fine.

I used the script in Greasemonkey and I can't download the audio file. The URL returns a 410 error:

HTTP/1.1 410 Gone
Last-Modified: Wed, 02 May 2007 10:26:10 GMT
Content-Type: text/plain
Content-Length: 0

**Comment by gantt** [comment]
One workaround is to edit the code and comment this line (#397 in the script version):

addFromManifest('140', '141'); // replace fmt140 with fmt141 if found in manifest

Replace it with:

// addFromManifest('140', '141'); // replace fmt140 with fmt141 if found in manifest

You'll be able to download the 128kbps audio file instead of 256kbps.
